#!/usr/bin/env python
"""Render docs/official-statistics-reference.md from the extracted statement JSON.

Generated from data, so the documentation can never drift from the extracted values.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from ml.data.official.load import OfficialStatement  # noqa: E402
from ml.data.official.validate import run_checks  # noqa: E402


def fmt(v) -> str:
    if v is None:
        return "blank"
    if isinstance(v, float):
        return f"{v:g}"
    return f"{v:,}" if abs(v) >= 10000 else str(v)


def main() -> int:
    st = OfficialStatement.load()
    doc = st.doc
    p = doc["periods"]
    out: list[str] = []
    w = out.append
    w("# Official statistics reference (generated)\n")
    w(
        "> Generated by `scripts/build_official_reference.py` from "
        "`data/official/mumbai_police_statement_2026-08.json`. Do not edit by hand.\n"
    )
    r = doc["report"]
    w(f"- Source file: `{r['source_file']}` (sha256 `{r['source_sha256'][:16]}...`)")
    w(f"- Jurisdiction: {r['jurisdiction']}")
    w(f"- Nature: **{r['data_nature']}** (not incident-level data)")
    w("- Periods:")
    for k, v in p.items():
        law = f", headed '{v['law_label_as_printed']}'" if v["law_label_as_printed"] else ""
        w(f"  - `{k}` {v['label']}: {v['start']} to {v['end']}{law}")
    w("")

    def val(section, head, period, metric):
        try:
            return st.value(section, head, period, metric)
        except KeyError:
            return None

    heads_by_section: dict[str, list[dict]] = {}
    for h in doc["heads"]:
        heads_by_section.setdefault(h["section"], []).append(h)
    titles = {s["id"]: (s["title"], s["page"]) for s in doc["sections"]}

    def reg_det_table(section: str, diff: bool) -> None:
        cols = [
            "Sr",
            "Code",
            "Official label (as printed)",
            "Aug-26 R/D",
            "Jul-26 R/D",
            "Jan-Aug 26 R/D (det %)",
            "Jan-Aug 25 R/D (det %)",
        ]
        if diff:
            cols.append("Diff (reg)")
        w("| " + " | ".join(cols) + " |")
        w("|" + "---|" * len(cols))
        for h in heads_by_section[section]:
            row = [h["sr"] or "", f"`{h['code']}`", h["label_as_extracted"]]
            for per in ("CM", "PM"):
                row.append(
                    f"{fmt(val(section, h['code'], per, 'registered'))} / "
                    f"{fmt(val(section, h['code'], per, 'detected'))}"
                )
            for per in ("CY", "PY"):
                row.append(
                    f"{fmt(val(section, h['code'], per, 'registered'))} / "
                    f"{fmt(val(section, h['code'], per, 'detected'))} "
                    f"({fmt(val(section, h['code'], per, 'detection_pct'))})"
                )
            if diff:
                row.append(fmt(val(section, h["code"], "CY_VS_PY", "difference_registered")))
            w("| " + " | ".join(row) + " |")
        w("")

    for sid in ("IPC", "CAW"):
        t, pg = titles[sid]
        w(f"## {t} (page {pg})\n")
        w("R = registered, D = detected. 'blank' = empty cell in the source (not zero).\n")
        reg_det_table(sid, diff=(sid == "IPC"))

    t, pg = titles["NDPS"]
    w(f"## {t} (page {pg}), August 2026\n")
    w(
        "| Code | Label | Cases | Persons arrested | Kg | Tablets | Litres | "
        "Value (unit not stated) |"
    )
    w("|---|---|---|---|---|---|---|---|")
    for h in heads_by_section["NDPS"]:
        c = h["code"]
        w(
            f"| `{c}` | {h['label_as_extracted']} | "
            + " | ".join(
                fmt(val("NDPS", c, "CM", m))
                for m in (
                    "cases",
                    "persons_arrested",
                    "quantity_kg",
                    "quantity_tablets",
                    "quantity_litres",
                    "value",
                )
            )
            + " |"
        )
    w("")

    t, pg = titles["BROTHELS"]
    w(f"## {t} (page {pg})\n")
    w("Only a Mumbai TOTAL row is printed (no zone breakdown).\n")
    w("| Code | Label | Aug-26 | Jan-Aug 26 | Jan-Aug 25 |")
    w("|---|---|---|---|---|")
    for h in heads_by_section["BROTHELS"]:
        c = h["code"]
        w(
            f"| `{c}` | {h['label']} | "
            + " | ".join(fmt(val("BROTHELS", c, per, "count")) for per in ("CM", "CY", "PY"))
            + " |"
        )
    w("")

    t, pg = titles["EOW"]
    w(f"## {t} (page {pg})\n")
    e = "EOW_CASES"
    w("| Metric | Value |")
    w("|---|---|")
    for per, m in (
        ("CM", "registered"),
        ("CM", "detected"),
        ("PM", "registered"),
        ("PM", "detected"),
        ("CY", "registered"),
        ("CY", "detected"),
        ("CY", "detection_pct"),
        ("PY", "registered"),
        ("PY", "detected"),
        ("CY_VS_PY", "difference_registered_as_printed"),
        ("CY", "property_involved_rs"),
    ):
        w(f"| {per} {m} | {fmt(val('EOW', e, per, m))} |")
    w("")

    t, pg = titles["CYBER"]
    w(f"## {t} (page {pg}), August 2026 only\n")
    w("'PA' is not defined in the source and is stored uninterpreted.\n")
    w("| Sr | Code | Label (as printed) | Parent | Reg. | Det. | PA |")
    w("|---|---|---|---|---|---|---|")
    for h in heads_by_section["CYBER"]:
        c = h["code"]
        w(
            f"| {h['sr'] or ''} | `{c}` | {h['label_as_extracted']} | {h['parent'] or ''} | "
            + " | ".join(fmt(val("CYBER", c, "CM", m)) for m in ("registered", "detected", "pa"))
            + " |"
        )
    w("")

    checks = run_checks(doc)
    bad = [c for c in checks if c["status"] != "pass"]
    w("## Consistency checks\n")
    w(
        f"{len(checks) - len(bad)} of {len(checks)} arithmetic checks pass. "
        "Discrepancies (values kept exactly as printed):\n"
    )
    w("| Check | Computed / expected | Printed |")
    w("|---|---|---|")
    for c in bad:
        w(f"| {c['description']} | {fmt(c['expected'])} | {fmt(c['observed'])} |")
    w("")
    w("## Extraction notes\n")
    for n in doc["extraction_notes"]:
        w(f"- {n}")
    w("")
    w("## Source notes\n")
    for n in doc["source_notes"]:
        w(f"- **{n['id']}**: {n['description']}")
    w("")

    target = ROOT / "docs" / "official-statistics-reference.md"
    target.write_text("\n".join(out), encoding="utf-8")
    print(f"Wrote {target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
