#!/usr/bin/env python
"""Render docs/model-card.md from the latest model bundle (numbers always match the run).

Usage:
    python scripts/build_model_card.py [--config configs/default.yaml] [--model-version V]
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from ml.config import LIMITATION_STATEMENT, load_config  # noqa: E402
from ml.models.registry import ModelBundle  # noqa: E402

LABELS = {
    "xgboost_calibrated": "XGBoost, isotonic-calibrated (deployed)",
    "xgboost_raw": "XGBoost, uncalibrated",
    "random_forest_calibrated": "Random Forest, isotonic-calibrated",
    "historical_rate_baseline": "Historical-rate baseline (Poisson, 52-week rate)",
    "crs_explainable": "Explainable CRS (score, ranking only)",
    "crs_components_logistic": "Logistic regression on the 7 CRS components",
    "blended_score": "Blended score (ranking only)",
}


def f(x, d=3):
    return "–" if x is None else f"{x:.{d}f}"


def pct(x):
    return "–" if x is None else f"{100 * x:.1f}%"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--config", default=None)
    ap.add_argument("--model-version", default=None)
    args = ap.parse_args()
    cfg = load_config(args.config)
    b = ModelBundle.load(cfg.paths.artifacts_dir / "models", args.model_version)
    md, m = b.metadata, b.metrics
    sp = md["splits"]
    out: list[str] = []
    w = out.append

    w("# Model card: CrimeX baseline forecaster\n")
    w(
        "> Generated by `scripts/build_model_card.py` from the model bundle. "
        "Re-run after training.\n"
    )
    w(
        f"**{md['data_label']}.** Every number below comes from synthetic demonstration data. "
        "It shows that the pipeline works end to end; it says nothing about real-world "
        "performance on Mumbai Police incident data.\n"
    )
    w("| | |")
    w("|---|---|")
    w(f"| Model version | `{md['model_version']}` |")
    w(f"| Trained | {md['trained_at']} ({md['training_seconds']} s) |")
    w(f"| Training dataset | `{md['training_dataset_version']}` |")
    w(f"| Feature set | `{md['feature_version']}` ({len(md['feature_names'])} features) |")
    w(f"| Crime types | {', '.join(md['crime_types'])} |")
    w(f"| Time bands | {', '.join(md['bands'])} |")
    w(f"| Forecast window | {md['window_days']} days |")
    w("")

    w("## Intended use\n")
    w(
        "- Decision support for police-station analysts: which zones, crime types and time bands "
        "show elevated predicted risk for the coming week, and why."
    )
    w(
        "- Output is always `Risk(zone, crime_type, time_window)` for aggregated 1.5 km grid "
        "zones. The model never scores individuals, households or demographic groups."
    )
    w(f"- {LIMITATION_STATEMENT}\n")
    w("## Out of scope\n")
    w("- Any person-level prediction, profiling or targeting.")
    w("- Automated enforcement decisions; an officer remains the decision-maker.")
    w("- Claims that an incident *will* occur, or causal claims about places.")
    w(
        "- Use on real data without re-validation "
        "(the current model is trained on synthetic data).\n"
    )

    w("## Targets\n")
    w(f"- **Classification (deployed):** {md['target']['classification']}")
    w(f"- **Regression:** {md['target']['regression']}\n")

    w("## Training procedure\n")
    w(
        f"- Chronological splits by forecast-window start with a boundary embargo "
        f"(windows straddling a split date are dropped). Train {sp['train']['first_window_start']} "
        f"→ {sp['train']['last_window_end']} ({sp['train']['origins']} weekly windows); validation "
        f"{sp['validation']['first_window_start']} → {sp['validation']['last_window_end']} "
        f"({sp['validation']['origins']}); test {sp['test']['first_window_start']} → "
        f"{sp['test']['last_window_end']} ({sp['test']['origins']})."
    )
    w(
        f"- Origins need {md['required_history_windows']} weeks of history, so the first year "
        "only feeds features."
    )
    w("- Percentile references for the F and S components are fitted on training origins only.")
    w(
        "- XGBoost (`binary:logistic`) and an XGBoost Poisson regressor are trained on the "
        "training split; the classifier is calibrated with isotonic regression on validation."
    )
    w(
        "- A Random Forest (calibrated the same way), a historical-rate baseline, the explainable "
        "CRS and a logistic fit on the CRS components are evaluated on identical windows."
    )
    w("- The recency half-life of component R is tuned per crime type on validation (CRS PR-AUC).")
    w(f"- XGBoost parameters: `{md['xgboost_params']}`\n")

    for split in ("validation", "test"):
        w(f"## Evaluation: {split} period\n")
        w(
            "| Model | PR-AUC | ROC-AUC | Brier | ECE | Precision | Recall | F1 | Top-10% capture "
            "| PAI |"
        )
        w("|---|---|---|---|---|---|---|---|---|---|")
        for name, r in m[split].items():
            tk = r["top_k"]
            w(
                f"| {LABELS.get(name, name)} | {f(r['pr_auc'])} | {f(r['roc_auc'])} | "
                f"{f(r.get('brier'), 4)} | {f(r.get('ece'), 4)} | {f(r.get('precision'), 2)} | "
                f"{f(r.get('recall'), 2)} | {f(r.get('f1'), 2)} | {pct(tk['capture_rate'])} | "
                f"{f(tk['pai'], 2)} |"
            )
        base = m[split]["xgboost_calibrated"]
        w(
            f"\nBase rate {pct(base.get('base_rate'))}. Top-K = {base['top_k']['k_zones']} zones "
            f"per (week, crime type, band); an oracle would capture "
            f"{pct(base['top_k']['oracle_capture_rate'])}. Precision/recall/F1 use thresholds "
            "chosen on validation. Scores that are not probabilities get ranking metrics only.\n"
        )

    w("## Expected counts (test)\n")
    w("| Model | MAE | RMSE | Poisson deviance |")
    w("|---|---|---|---|")
    for name, r in m["test_counts"].items():
        w(f"| {name} | {f(r['mae'], 4)} | {f(r['rmse'], 4)} | {f(r['poisson_deviance'], 4)} |")
    w("")

    w("## Per crime type (test)\n")
    w("| Crime type | Base rate | XGBoost PR-AUC | XGBoost Brier | CRS PR-AUC | XGBoost top-10% |")
    w("|---|---|---|---|---|---|")
    tk = m["test"]["xgboost_calibrated"]["top_k"]["per_crime_type"]
    for c, r in m["test_per_crime_type"].items():
        w(
            f"| {c} | {pct(r['base_rate'])} | {f(r['xgboost_calibrated']['pr_auc'])} | "
            f"{f(r['xgboost_calibrated']['brier'], 4)} | {f(r['crs_explainable']['pr_auc'])} | "
            f"{pct(tk.get(c))} |"
        )
    w("")

    w("## Calibration (test, 10 quantile bins)\n")
    w("| Mean predicted | Observed rate | Rows |")
    w("|---|---|---|")
    for r in m["reliability"]["test"]:
        w(f"| {pct(r['mean_predicted'])} | {pct(r['observed_rate'])} | {r['n']:,} |")
    w("")

    w("## What the model relies on (mean |SHAP|, test sample)\n")
    w("| Input | Mean abs SHAP (log-odds) |")
    w("|---|---|")
    for r in md["mean_abs_shap_test_sample"][:12]:
        w(f"| {r['label']} | {r['mean_abs_shap']:.4f} |")
    w("")

    w("## Explainable score weights\n")
    w("| Signal | Configured weight | Logistic fit (normalised, non-negative) |")
    w("|---|---|---|")
    for k, v in md["crs_weights_configured"].items():
        s = md["crs_weights_suggested_by_logistic_fit"].get(k)
        w(f"| {k} | {v:.2f} | {'–' if s is None else f'{s:.2f}'} |")
    w(
        "\nThe logistic fit is reported for comparison only; changing the configured weights is "
        "a human decision (`configs/default.yaml → scoring.crs_weights`).\n"
    )
    w(
        "Tuned recency half-lives (days): "
        + ", ".join(f"{k} {v['chosen']:g}" for k, v in md["recency_half_life_tuning"].items())
        + ".\n"
    )

    w("## Findings on this run\n")
    t = m["test"]
    w(
        f"- The calibrated XGBoost beats the historical-rate baseline on every probability "
        f"metric but only modestly (test PR-AUC {f(t['xgboost_calibrated']['pr_auc'])} vs "
        f"{f(t['historical_rate_baseline']['pr_auc'])}; top-10% capture "
        f"{pct(t['xgboost_calibrated']['top_k']['capture_rate'])} vs "
        f"{pct(t['historical_rate_baseline']['top_k']['capture_rate'])}). Most of the synthetic "
        "signal is stable spatial concentration, which a long-run rate already captures; the "
        "gains come from emerging hotspots, surges and rare crime types."
    )
    w(
        f"- The Random Forest is statistically indistinguishable from XGBoost "
        f"(PR-AUC {f(t['random_forest_calibrated']['pr_auc'])}). "
        "Deep spatiotemporal models are not "
        "justified until they beat this baseline on real data."
    )
    w(
        f"- The hand-weighted CRS ranks less well when pooled across crime types (PR-AUC "
        f"{f(t['crs_explainable']['pr_auc'])}) because its F and S components are percentiles "
        "within each crime type; within a crime type it separates well (see the per-type table). "
        "It is kept as the explanation layer, not as the most accurate ranker."
    )
    w("- Calibration on the held-out period is close to the diagonal (see the table above).\n")

    w("## Ethical considerations and limitations\n")
    w(
        "- **Synthetic training data.** Patterns were planted by the generator; real reported "
        "data will contain reporting bias, under-reporting and recording practices that the "
        "synthetic data does not."
    )
    w(
        "- **Feedback loops.** Directing attention to flagged zones can raise recorded incidents "
        "there. Monitor with officer feedback and periodic re-evaluation "
        "before any operational use."
    )
    w("- **Association, not causation.** Affinity and risk describe historical reported patterns.")
    w(
        "- **Small counts.** Rare heads (e.g. Robbery Chain Snatching) have very low base rates; "
        "their probabilities carry wide uncertainty, reflected in the LOW confidence label."
    )
    w("- **Scope.** Zone-level only; no personal, demographic or individual data is used.")
    w("")
    target = ROOT / "docs" / "model-card.md"
    target.write_text("\n".join(out), encoding="utf-8")
    print(f"Wrote {target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
